# Generated by Django 3.1.8 on 2021-08-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default='Place Holder', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Place Holder', max_length=255, unique=True),
        ),
    ]
